@startuml
  class CRD_DeviceRequest{
    code: OxygenDevice
  }
  CRD_DeviceRequest --|> DeviceRequest
  CRD_DeviceRequest -> Patient : subject
  CRD_DeviceRequest -> Encounter: encounter
  CRD_DeviceRequest -> Practitioner: performer
  CRD_DeviceRequest -> Coverage: insurance

  Coverage -> Patient : benficiary
  Coverage -> Organization: payor
  Encounter -> Patient
  Encounter -> Practitioner
@enduml
