
@startuml


    [*] --> TopicCreated: login

    state TopicCreated{
    '    [*] --> Active: open(i)/ curI=i, ilist+=i, curP=i.patient
        [*] --> InActive
        state fork_state <<fork>>

        InActive --> Active : open(p)/ curP=p, plist+=p

        Active--> Active: open(p)/ plist+p, curP=p

        Active--> fork_state: close(p)
        fork_state --> Active: plist.size>1/ plist-=p, curP=plist[0]
        fork_state --> InActive: plist.size==1/ plist-=p

        --
        [*] --> InActive2
        state fork_state2 <<fork>>

        InActive2 --> Active2 : open(p) / send(openPatient(p))
        Active2 --> Active2: open(p) / send(openPatient(p)
        Active2 --> fork_state2: close(p)
        fork_state2 --> InActive2: list.size<=1 / send(closePatient(p)
        fork_state2 --> Active2: list.size>1 / send(closePatient(p)
    }

    TopicCreated --> [*] : logout/ A(list):send(closePatient(p), send(logout)
@enduml
