@startuml

[HapiR4]
() "FHIR" as fhir
fhir - HapiR4

package "fc"{
topicMgmt - [FhirCastHub]
[FhirCastHub] - fhircast
}

package "worklist" {
    [WorkListClient] --> WorkListServer
    note left of WorkListClient : holds Context
    package "WorkListServer" {
        () "FHIR" as secfhir
        [SmartOnFhirR4]
        [WorkListServer] ..> secfhir
        secfhir - [SmartOnFhirR4]

        note right of WorkListServer
            also SmartOnFhirR4?
            yes - launch and topic context
            needs to be managed
        end note

        note left of SmartOnFhirR4
         Needs to act on launch scope.
         Launch context has to be known.
        end note
    }
    [WorkListClient] --> fhircast
    [WorkListClient] --> topicMgmt
    [SmartOnFhirR4] --> fhir
}

[SmartOnFhirApp]
launch -[SmartOnFhirApp]
[SmartOnFhirApp] --> fhircast
[SmartOnFhirApp] --> secfhir
[WorkListClient] --> launch





@enduml